### ISSUE TITLE
Ужасная БД

### ISSUE THREAD

**Issue by Mazgagzam** [mrstirlitz1221/_ylKarakol_#1]
Переходи на MazgaDB гей и чё за гкод, на 3 перешёл но гкодишь

**Comment by mrstirlitz1221** [comment]
Я хз как там рассылку сообщений зафигачить

чт, 8 июн. 2023 г., 11:35 Mazgagzam ***@***.***>:

**Comment by Mazgagzam** [comment]
Мда

**Comment by mrstirlitz1221** [comment]
Ну вот как то так

пт, 9 июн. 2023 г., 13:16 Mazgagzam ***@***.***>:

**Comment by Mazgagzam** [comment]
Берешь достаешь все значения из бд и вот тебе все айди

**Comment by mrstirlitz1221** [comment]
Я нефор, на 2 ебашу и мне по кайфу жи есть 🐱🍓

чт, 8 июн. 2023 г., 11:35 Mazgagzam ***@***.***>:

**Comment by Mazgagzam** [comment]
Пздц

**Comment by mrstirlitz1221** [comment]
I'm a clown 🤡

вс, 15 окт. 2023 г., 09:46 Mazgagzam ***@***.***>:

**Comment by Mazgagzam** [comment]
Все с тобой понятно

**Comment by Mazgagzam** [comment]
Кххкхк
